FROM node:22.15.0

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Torna o script de entrada disponível
COPY entrypoint.sh /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]

EXPOSE 3001
