services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vehicle_tracking
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tracking_network

  central-tracking-service:
    build:
      context: .
      dockerfile: central-tracking-service/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/vehicle_tracking?schema=public
    volumes:
      - ./protos:/app/protos
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - tracking_network

  eta-service:
    build:
      context: .
      dockerfile: eta-service/Dockerfile
    volumes:
      - ./protos:/app/protos
      - ./eta-service/src:/app/src
    environment:
      - TRACKING_SERVICE_HOST=central-tracking-service
      - TRACKING_SERVICE_PORT=50051
    ports:
      - "50052:50052"
    depends_on:
      - central-tracking-service
    restart: unless-stopped
    networks:
      - tracking_network

  express-grpc-gateway:
    build:
      context: .
      dockerfile: express-grpc-gateway/Dockerfile
    volumes:
      - ./protos:/app/protos
    ports:
      - "3001:3001"
    environment:
      - TRACKING_SERVICE_HOST=central-tracking-service
      - TRACKING_SERVICE_PORT=50051
      - ETA_SERVICE_HOST=eta-service
      - ETA_SERVICE_PORT=50052
    depends_on:
      - central-tracking-service
      - eta-service
    restart: unless-stopped
    networks:
      - tracking_network

  frontend:
    build:
      context: ./vehicle-tracking-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./vehicle-tracking-frontend/src:/app/src
      - ./vehicle-tracking-frontend/public:/app/public
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_WS_URL=ws://localhost:3001
    depends_on:
      - express-grpc-gateway
    restart: unless-stopped
    networks:
      - tracking_network

  vehicle-client-1:
    build:
      context: .
      dockerfile: vehicle-grpc-client/Dockerfile
    volumes:
      - ./protos:/app/protos
      - ./vehicle-grpc-client/GPX:/app/GPX
    depends_on:
      - central-tracking-service
    command: node dist/client.js --file GPX/CampusJBG-Recife.gpx --id carro-01 --server central-tracking-service:50051 --vel 200
    restart: unless-stopped
    networks:
      - tracking_network

  vehicle-client-2:
    build:
      context: .
      dockerfile: vehicle-grpc-client/Dockerfile
    volumes:
      - ./protos:/app/protos
      - ./vehicle-grpc-client/GPX:/app/GPX
    depends_on:
      - central-tracking-service
    command: node dist/client.js --file GPX/CampusJBG-Piedade.gpx --id van-01 --server central-tracking-service:50051 --vel 150
    restart: unless-stopped
    networks:
      - tracking_network

  eta-client:
    build:
      context: .
      dockerfile: eta-service/Dockerfile
    container_name: eta-client
    volumes:
      - ./protos:/app/protos
      - ./eta-service/src:/app/src
    environment:
      - TRACKING_SERVICE_HOST=central-tracking-service
      - TRACKING_SERVICE_PORT=50051
      - ETA_SERVICE_HOST=eta-service
      - ETA_SERVICE_PORT=50052
    depends_on:
      - central-tracking-service
      - eta-service
    restart: unless-stopped
    networks:
      - tracking_network
    command: >
      sh -c "
      echo 'Waiting for services to be ready...' &&
      sleep 35 &&
      node dist/eta-client.js
      "
    tty: true
    stdin_open: true

networks:
  tracking_network:
    driver: bridge

volumes:
  postgres_data:
